### ISSUE TITLE
机器学习求助

### ISSUE THREAD

**Issue by Auxotaku** [LecterChu/nwpu-cram#36]
zwp老师的机器学习课程考核难度大吗？
想知道有哪些题型orz

**Comment by LecterChu** [comment]
实在抱歉 我和周围的同学基本都没上过机器学习😭 也不是非常了解

**Comment by Auxotaku** [comment]
想起来了这个问题
出分后来答一下
考核难度：低
题目类型：名词解释 简答
给分：高
和课堂上大量的公式推导形成了较大的反差（
